/**
 * iOS PWA startup images. GENERATED by scripts/build-brand-assets.ts — edit the
 * device table there, not here.
 *
 * Next's metadata API has no apple-touch-startup-image field, so the layout
 * renders these as <link> elements and lets React hoist them into <head>.
 * Without them iOS shows a blank white frame between the icon tap and first
 * paint, which is the one thing the brand spec says must never happen.
 */
export const APPLE_STARTUP_IMAGES: ReadonlyArray<{ href: string; media: string }> = [
  // iPhone 11, XR
  {
    href: "/splash/iphone-xr.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPhone 11 Pro, 12 mini, 13 mini, X, XS
  {
    href: "/splash/iphone-x.png",
    media:
      "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 11 Pro Max, XS Max
  {
    href: "/splash/iphone-xs-max.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 12, 13, 14
  {
    href: "/splash/iphone-12.png",
    media:
      "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 12/13 Pro Max, 14 Plus
  {
    href: "/splash/iphone-12-pro-max.png",
    media:
      "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 14 Pro, 15, 15 Pro, 16
  {
    href: "/splash/iphone-14-pro.png",
    media:
      "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 14/15 Pro Max, 15 Plus, 16 Plus
  {
    href: "/splash/iphone-14-pro-max.png",
    media:
      "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 16 Pro
  {
    href: "/splash/iphone-16-pro.png",
    media:
      "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPhone 16 Pro Max
  {
    href: "/splash/iphone-16-pro-max.png",
    media:
      "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  // iPad 9.7", iPad mini 4/5
  {
    href: "/splash/ipad-97.png",
    media:
      "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad 9.7", iPad mini 4/5 (landscape)
  {
    href: "/splash/ipad-97-landscape.png",
    media:
      "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad mini 6, mini 7
  {
    href: "/splash/ipad-mini-6.png",
    media:
      "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad mini 6, mini 7 (landscape)
  {
    href: "/splash/ipad-mini-6-landscape.png",
    media:
      "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad Air 10.9", iPad 10th/11th gen
  {
    href: "/splash/ipad-109.png",
    media:
      "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad Air 10.9", iPad 10th/11th gen (landscape)
  {
    href: "/splash/ipad-109-landscape.png",
    media:
      "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad Pro 11" 1st–4th gen
  {
    href: "/splash/ipad-pro-11.png",
    media:
      "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad Pro 11" 1st–4th gen (landscape)
  {
    href: "/splash/ipad-pro-11-landscape.png",
    media:
      "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad Pro 11" M4, Air 11" M2
  {
    href: "/splash/ipad-pro-11-m4.png",
    media:
      "(device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad Pro 11" M4, Air 11" M2 (landscape)
  {
    href: "/splash/ipad-pro-11-m4-landscape.png",
    media:
      "(device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad Pro 12.9", Air 13" M2
  {
    href: "/splash/ipad-pro-129.png",
    media:
      "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad Pro 12.9", Air 13" M2 (landscape)
  {
    href: "/splash/ipad-pro-129-landscape.png",
    media:
      "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
  // iPad Pro 13" M4
  {
    href: "/splash/ipad-pro-13-m4.png",
    media:
      "(device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
  },
  // iPad Pro 13" M4 (landscape)
  {
    href: "/splash/ipad-pro-13-m4-landscape.png",
    media:
      "(device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)",
  },
];
