import { NextResponse, type NextRequest } from "next/server";
import { DC_GROUPS, DC_MISTAKES, EMPTY_DC, dcJudge, dcPayload, type DcVerdict } from "../../../../lib/depth-chart";
import { fetchDcPractice } from "../../../../lib/practice-data";
import { createClient } from "../../../../lib/supabase/server";
import { createServiceClient } from "../../../../lib/supabase/service";

export const dynamic = "force-dynamic";

const NO_STATS = { streak: 0, bestStreak: 0, played: 0, won: 0 };

/**
 * Depth Chart, unscored (PRAC-1). No write anywhere in this file.
 *
 * These boards came out of `buildDepthChart` unchanged, so every one has passed
 * the same uniqueness, rival-category and trap checks a real board has. That is
 * why they are generated by the job and stored rather than made on demand: a
 * fair board costs up to 800 validated draws, and an unfair board is not an
 * acceptable thing to hand somebody as practice.
 *
 * The board state is rebuilt by replaying the client's submissions through
 * `dcJudge`, so which groups are solved and how many mistakes stand are the
 * server's conclusions. A client naming a group id it did not earn gets nothing:
 * `solved` is derived here, never accepted.
 */
async function signedIn() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user !== null;
}

export async function GET(req: NextRequest) {
  if (!(await signedIn())) return NextResponse.json({ error: "Sign in to play" }, { status: 401 });

  const idParam = new URL(req.url).searchParams.get("id");
  const id = idParam === null ? null : Number(idParam);
  if (id !== null && !Number.isInteger(id)) {
    return NextResponse.json({ error: "Bad request" }, { status: 400 });
  }

  const r = await fetchDcPractice(createServiceClient(), id);
  if (!r) return NextResponse.json({ error: "No practice boards yet" }, { status: 404 });

  return NextResponse.json({
    practiceId: r.id,
    crests: r.crests,
    ...dcPayload("practice", r.grid, EMPTY_DC, NO_STATS),
  });
}

export async function POST(req: NextRequest) {
  if (!(await signedIn())) return NextResponse.json({ error: "Sign in to play" }, { status: 401 });

  let id: number;
  let submissions: number[][];
  try {
    const body = (await req.json()) as { id?: unknown; guesses?: unknown };
    id = Number(body.id);
    submissions = Array.isArray(body.guesses)
      ? body.guesses.map((g) => (Array.isArray(g) ? g.map(Number) : []))
      : [];
  } catch {
    return NextResponse.json({ error: "Bad request" }, { status: 400 });
  }
  if (!Number.isInteger(id) || submissions.length === 0 || submissions.length > 16) {
    return NextResponse.json({ error: "Bad request" }, { status: 400 });
  }

  const r = await fetchDcPractice(createServiceClient(), id);
  if (!r) return NextResponse.json({ error: "No such board" }, { status: 404 });

  const onBoard = new Set(r.grid.tiles);
  const latest = submissions[submissions.length - 1]!;
  if (latest.length !== 4 || new Set(latest).size !== 4 || latest.some((t) => !onBoard.has(t))) {
    return NextResponse.json({ error: "Pick four from this board" }, { status: 422 });
  }

  /* Replay every submission. `solved` and `mistakes` are conclusions drawn here
     rather than values accepted, so naming a group id reveals nothing. */
  const solved: string[] = [];
  const guesses: Array<{ teamIds: number[]; verdict: DcVerdict }> = [];
  let mistakes = 0;
  for (const g of submissions) {
    if (mistakes >= DC_MISTAKES || solved.length >= DC_GROUPS) break;
    if (g.length !== 4 || new Set(g).size !== 4 || g.some((t) => !onBoard.has(t))) continue;
    const { verdict, groupId } = dcJudge(g, r.grid.groups);
    guesses.push({ teamIds: g, verdict });
    if (verdict === "correct" && groupId && !solved.includes(groupId)) solved.push(groupId);
    else if (verdict !== "correct") mistakes += 1;
  }

  const entry = { ...EMPTY_DC, solved, mistakes, guesses };
  return NextResponse.json({
    practiceId: r.id,
    crests: r.crests,
    lastVerdict: guesses[guesses.length - 1]?.verdict ?? "wrong",
    ...dcPayload("practice", r.grid, entry, NO_STATS),
  });
}
