-- TAPE-1 — The Tape: one game from the archive a day, five questions about it.
--
-- Replaces Guess the Game's mechanic (owner, 2026-08-18: "way too random…
-- hardly any trivia, just trying to randomly guess a team"). That puzzle hid
-- the game and asked you to name it out of 266 schools; this one names the game
-- and asks what happened in it, which is a football question with a knowledge
-- gradient instead of a one-in-266 guess.
--
-- ## Generated by a job, not computed on read — and that is GTG-1's lesson
--
-- Guess the Game picks its puzzle by hashing the day against a deck read at
-- request time. No job, no cadence, and therefore no watchdog lane: when the
-- deck turned out to be empty it stayed empty for weeks and NOTHING WENT RED,
-- because there was nothing that could be late. `daily-puzzles` generates a
-- queue of days ahead of time, so queue depth is a health metric and the job
-- goes red days before any player sees an empty screen.
--
-- The rendezvous hash is still what picks the game; it moved inside the
-- generator rather than being replaced, so "same puzzle for everyone, stable
-- as the deck grows" survives intact.
--
-- ## The answers are frozen here, which is why there is no grading lane
--
-- `six_pack_questions` stores questions about FUTURE games and grades them
-- later; its `answer` column is null until a job settles it, and the questions
-- are publicly readable because the answers do not exist yet. Both facts invert
-- here. These games were played years ago, so a question is only minted if its
-- answer is already computable, and the answer is written with it. There is no
-- pending state and no re-grade — a corrected poll row landing next season
-- cannot restate an answer somebody was already scored against.
--
-- Which also means `tape_questions` can NEVER be publicly readable: it is the
-- answer key. It carries no select policy at all and every read goes through
-- /api/tape on the service client.
--
-- ## What this game does not promise, stated so nobody claims it later
--
-- The fixture is named up front — that is the hook — so every fact about it is
-- public. `games`, `line_snapshots` and `poll_rankings` are all anon-readable
-- (migration 0011), and more decisively the answers are on the open internet.
-- Withholding the score from the payload is worth doing; calling it an
-- anti-spoiler property is not. Guess the Game's contract worked because the
-- game's IDENTITY was hidden. Here, looking it up is the same as not playing,
-- and that is a social contract in a fifteen-person crew, not a technical one.
--
-- ## Apply-vs-deploy order: APPLY FIRST
--
-- The page selects `tape_puzzles`, so deploying it against a database without
-- this migration fails the read loudly.

-- The day's fixture. Readable — "there is a puzzle today, and it is this game"
-- is the screen, not the answer.
create table public.tape_puzzles (
  day        date primary key,
  game_id    integer not null references public.games(id),
  created_at timestamptz not null default now()
);

alter table public.tape_puzzles enable row level security;

-- **The date gate is a timezone trap, and it is why this is not `current_date`.**
-- The generator banks two weeks ahead, so this table always holds future rows.
-- `current_date` resolves in the SESSION timezone, which on Supabase is UTC,
-- while `productDate()` — the one definition of "today" this product has
-- (src/lib/streak.ts) — is America/Chicago. Between 00:00 and 06:00 UTC those
-- disagree, so a player refreshing at 7pm Central on Tuesday would be served
-- Wednesday's fixture. The conversion is explicit and pinned by a pgTAP test
-- that sets the session timezone to UTC first.
create policy "read tape puzzles once the day has arrived" on public.tape_puzzles
  for select to authenticated, anon
  using (day <= (now() at time zone 'America/Chicago')::date);

revoke insert, update, delete, truncate on public.tape_puzzles
  from public, anon, authenticated;

-- The answer key. RLS on, and DELIBERATELY NO SELECT POLICY — not for anon,
-- not for authenticated, not gated on the date. RLS with no policy denies
-- every row, which is exactly right: the route is the only reader, on the
-- service client, and it ships one question at a time.
--
-- Considered and rejected: a column grant (`revoke select (answer) …`, the
-- 0040/0052 pattern). It works, but PostgREST's `select *` ERRORS on a revoked
-- column rather than omitting it, so every incidental reader breaks instead of
-- degrading — and the row also has to hide future questions, which a column
-- grant cannot express.
create table public.tape_questions (
  day     date     not null references public.tape_puzzles(day) on delete cascade,
  idx     smallint not null check (idx between 0 and 4),
  kind    text     not null,
  -- Worded at generation, not at read: the question a player answered must not
  -- be re-phrased by a later deploy.
  prompt  text     not null,
  choices text[]   not null check (array_length(choices, 1) between 2 and 4),
  -- Frozen. Never null — a question with no answer is never minted.
  answer  text     not null,
  primary key (day, idx)
);

alter table public.tape_questions enable row level security;
revoke insert, update, delete, truncate on public.tape_questions
  from public, anon, authenticated;

-- One row per player per day. `answers` is an APPEND-ONLY jsonb array of
-- {idx, choice, correct}; the route refuses a POST whose idx is not the next
-- one, so "no going back" is server-enforced rather than a client convention.
--
-- `correct` is stored rather than recomputed on read, the same call GTG-9 made
-- for its chip marks: a reload must show the round you actually played, and
-- recomputing would put the answer key on every GET path.
create table public.tape_entries (
  user_id      uuid not null references auth.users(id) on delete cascade,
  day          date not null references public.tape_puzzles(day) on delete cascade,
  answers      jsonb not null default '[]',
  correct      smallint not null default 0 check (correct between 0 and 5),
  completed_at timestamptz,
  updated_at   timestamptz not null default now(),
  primary key (user_id, day)
);

alter table public.tape_entries enable row level security;

create policy "read own tape entries" on public.tape_entries
  for select to authenticated
  using (user_id = (select auth.uid()));

-- All writes through the route (service role): grading needs the answer key,
-- and the answer key is not readable by the caller.
revoke insert, update, delete, truncate on public.tape_entries
  from public, anon, authenticated;

-- The board without the spoilers: how many days, how many right, how many
-- clean sheets. Aggregates only — never a day's answers, and never which
-- questions anybody missed.
--
-- Scoring lives HERE, in SQL, for the same reason Guess the Game's does:
-- `arcade.ts` consumes the column rather than re-deriving it, and a copy of a
-- points formula in a second language is the thing that drifts silently and
-- re-scores a season.
create or replace function public.tape_leaderboard()
returns table (user_id uuid, played integer, correct integer, clean integer, points integer)
language sql
security definer
stable
set search_path = ''
as $$
  select e.user_id,
         count(*) filter (where e.completed_at is not null)::integer,
         coalesce(sum(e.correct) filter (where e.completed_at is not null), 0)::integer,
         count(*) filter (where e.completed_at is not null and e.correct = 5)::integer,
         coalesce(
           sum(e.correct + case when e.correct = 5 then 3 else 0 end)
             filter (where e.completed_at is not null),
           0)::integer
  from public.tape_entries e
  group by e.user_id;
$$;

revoke execute on function public.tape_leaderboard() from public, anon;
grant  execute on function public.tape_leaderboard() to authenticated;
